/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BusinessHours: typeof import('./src/components/BusinessHours.vue')['default']
    MenuEditor: typeof import('./src/components/MenuEditor.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RestaurantCard: typeof import('./src/components/RestaurantCard.vue')['default']
    RestaurantForm: typeof import('./src/components/RestaurantForm.vue')['default']
    RestaurantManager: typeof import('./src/components/RestaurantManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarRating: typeof import('./src/components/StarRating.vue')['default']
  }
}
