/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/historys': RouteRecordInfo<'/admin/historys', '/admin/historys', Record<never, never>, Record<never, never>>,
    '/admin/menus': RouteRecordInfo<'/admin/menus', '/admin/menus', Record<never, never>, Record<never, never>>,
    '/admin/oldOrders': RouteRecordInfo<'/admin/oldOrders', '/admin/oldOrders', Record<never, never>, Record<never, never>>,
    '/admin/orders': RouteRecordInfo<'/admin/orders', '/admin/orders', Record<never, never>, Record<never, never>>,
    '/admin/products': RouteRecordInfo<'/admin/products', '/admin/products', Record<never, never>, Record<never, never>>,
    '/admin/restaurants': RouteRecordInfo<'/admin/restaurants', '/admin/restaurants', Record<never, never>, Record<never, never>>,
    '/admin/reviews': RouteRecordInfo<'/admin/reviews', '/admin/reviews', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/oldOrders': RouteRecordInfo<'/oldOrders', '/oldOrders', Record<never, never>, Record<never, never>>,
    '/orders/': RouteRecordInfo<'/orders/', '/orders', Record<never, never>, Record<never, never>>,
    '/orders/create': RouteRecordInfo<'/orders/create', '/orders/create', Record<never, never>, Record<never, never>>,
    '/orders/history': RouteRecordInfo<'/orders/history', '/orders/history', Record<never, never>, Record<never, never>>,
    '/product/[id]': RouteRecordInfo<'/product/[id]', '/product/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/restaurants/': RouteRecordInfo<'/restaurants/', '/restaurants', Record<never, never>, Record<never, never>>,
    '/restaurants/[id]': RouteRecordInfo<'/restaurants/[id]', '/restaurants/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/restaurants/[id]/edit': RouteRecordInfo<'/restaurants/[id]/edit', '/restaurants/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/restaurants/add': RouteRecordInfo<'/restaurants/add', '/restaurants/add', Record<never, never>, Record<never, never>>,
    '/restaurants/create': RouteRecordInfo<'/restaurants/create', '/restaurants/create', Record<never, never>, Record<never, never>>,
    '/restaurants/detail': RouteRecordInfo<'/restaurants/detail', '/restaurants/detail', Record<never, never>, Record<never, never>>,
    '/restaurants/edit/[id]': RouteRecordInfo<'/restaurants/edit/[id]', '/restaurants/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/restaurants/form': RouteRecordInfo<'/restaurants/form', '/restaurants/form', Record<never, never>, Record<never, never>>,
  }
}
